import { DesignerType, Question, TypeInfo } from './types';

export const typeData: Record<DesignerType, TypeInfo> = {
  kameleon: {
    id: 'kameleon',
    name: 'Kaméleon',
    emoji: '🦎',
    color: '#10B981',
    shortDescription: 'A stílusok mestere – bárhol otthon vagy.',
    longDescription: 'Te vagy az, aki hétfőn egy minimalista tech brandot, kedden egy retro sörmárkát csinál – és mindkettő autentikusnak tűnik. Nem hagyod ott az ujjlenyomatod, és ez a szuperképességed. A stúdiók imádnak téged, mert bármilyen projektre rá tudsz állni. A veszély? Néha elfelejtkezhetsz arról, hogy mi a saját hangod.',
  },
  kivitelezo: {
    id: 'kivitelezo',
    name: 'Kivitelező sztár',
    emoji: '⚡',
    color: '#F59E0B',
    shortDescription: 'Pixel-perfect, határidőre, minden alkalommal.',
    longDescription: 'Te vagy az, akit akkor hívnak, amikor valaminek tökéletesnek kell lennie – és tegnapra. Nem kell inspirációra várnod, egyszerűen csinálod. A szoftvered? Ismered, mint a tenyered. A korlátod: jó briefre van szükséged. Ha az megvan, gépként működsz. Ha nincs, frusztrált leszel.',
  },
  vizionarius: {
    id: 'vizionarius',
    name: 'Vízionárius',
    emoji: '🚀',
    color: '#8B5CF6',
    shortDescription: 'A nagy ötletek embere – a doboz nem is létezik számodra.',
    longDescription: 'Te nem a brief felét olvasod, hanem olyan kérdésekkel jössz vissza, amik az egész projektet új szintre emelik. Nem vagy seggfej és nem vagy lusta – egyszerűen a fejed máshol jár. A termelési munka nem neked való, de a koncepciófázisban felbecsülhetetlen vagy.',
  },
  rendszerepito: {
    id: 'rendszerepito',
    name: 'Rendszerépítő',
    emoji: '🔧',
    color: '#6B7280',
    shortDescription: 'Te tartod össze a káoszt – láthatatlanul.',
    longDescription: 'Nem a vizuális ragyogás a te területed, hanem a struktúra. Te vagy, aki rendszert lát ott, ahol mások káoszt. Design rendszerek, komponens könyvtárak, logikus flow-k – ez a te világod. A munkád akkor a legjobb, ha senki nem veszi észre, mert minden "csak működik".',
  },
  kulturakutato: {
    id: 'kulturakutato',
    name: 'Kultúrakutató',
    emoji: '🔍',
    color: '#EC4899',
    shortDescription: 'A trendek és a "miért" szakértője.',
    longDescription: 'Te vagy, aki már tudja, mi lesz menő három hónap múlva. Szubkultúrákban, niche közösségekben mozgasz otthonosan, és zseniálisan dekódolsz kulturális jeleket. A kivitelezés nem az erősséged, de a discovery fázisban és a stratégiai döntéseknél nélkülözhetetlen vagy.',
  },
  hid: {
    id: 'hid',
    name: 'Híd',
    emoji: '🌉',
    color: '#06B6D4',
    shortDescription: 'A fordító – kreatív és üzleti világ között.',
    longDescription: 'Te vagy, aki megérti, hogy amikor a kliens azt mondja "nem tetszik ez a kék", valójában azt akarja mondani: "nem érzem elég prémiumnak". Aztán ezt úgy viszed vissza a csapatnak, hogy senki ne sértődjön meg. Híd-emberből kevés van – ha te az vagy, aranyat érsz.',
  },
  kiserletezo: {
    id: 'kiserletezo',
    name: 'Kísérletező',
    emoji: '🧪',
    color: '#22C55E',
    shortDescription: 'Mindig egy lépéssel az iparág előtt.',
    longDescription: 'Te már Figmáztál, amikor mások még Sketchben gondolkodtak. Most valószínűleg AI toolokkal játszol. A kockázat? Néha a tool fontosabb neked, mint a probléma. De a csapatnak szüksége van rád, mert nélküled lemaradnak. Te hozod be az új lehetőségeket.',
  },
  stratega: {
    id: 'stratega',
    name: 'Stratéga',
    emoji: '🎯',
    color: '#EF4444',
    shortDescription: 'A "miért" embere – a nagy kép látója.',
    longDescription: 'Te nem a pixelekkel kezded, hanem a kérdésekkel. "Miért csináljuk ezt? Kinek? Mi a cél?" A vizuális nem feltétlenül az erősséged, de az üzleti gondolkodás igen. Te vagy, aki megspórolja a csapatnak a rossz irányba tett lépéseket.',
  },
};

export const questions: Question[] = [
  {
    id: 0,
    text: 'Új projekt briefje érkezik. Mi az első gondolatod?',
    answers: [
      { id: 'A', text: 'Milyen stílusban képzelik el? Mutassatok referenciákat!', scores: { kameleon: 2 } },
      { id: 'B', text: 'Van már wireframe vagy struktúra, amiből dolgozhatok?', scores: { kivitelezo: 2 } },
      { id: 'C', text: 'Mi lenne, ha teljesen másképp közelítenénk meg?', scores: { vizionarius: 2 } },
      { id: 'D', text: 'Álljunk meg – pontosan mi a probléma, amit meg akarunk oldani?', scores: { stratega: 2 } },
      { id: 'E', text: 'Milyen rendszerekhez kell majd illeszkednie?', scores: { rendszerepito: 2 } },
    ],
  },
  {
    id: 1,
    text: 'Mi frusztrál a legjobban egy projektben?',
    answers: [
      { id: 'A', text: 'Amikor nincs egyértelmű iránymutatás, és találgatnom kell', scores: { kivitelezo: 2 } },
      { id: 'B', text: 'Amikor a kliens és a csapat folyamatosan félreérti egymást', scores: { hid: 2 } },
      { id: 'C', text: 'Amikor ragaszkodnak az elavult eszközökhöz és módszerekhez', scores: { kiserletezo: 2 } },
      { id: 'D', text: 'Amikor nincs idő a kutatásra és a "miért" megértésére', scores: { kulturakutato: 2, stratega: 1 } },
      { id: 'E', text: 'Amikor túl szűk keretek között kell maradnom', scores: { vizionarius: 2 } },
    ],
  },
  {
    id: 2,
    text: 'Egy brainstorming sessionön általában te vagy az, aki...',
    answers: [
      { id: 'A', text: '...sok különböző irányba tudja vinni a beszélgetést, stílustól függően', scores: { kameleon: 2 } },
      { id: 'B', text: '...rákérdez a kontextusra és a célközönségre', scores: { kulturakutato: 2 } },
      { id: 'C', text: '...összeköti a kreatív ötleteket az üzleti célokkal', scores: { stratega: 2, hid: 1 } },
      { id: 'D', text: '...teljesen vad ötletekkel áll elő', scores: { vizionarius: 2 } },
      { id: 'E', text: '...már azon gondolkodik, hogyan lesz ebből működő rendszer', scores: { rendszerepito: 2 } },
    ],
  },
  {
    id: 3,
    text: 'Szabadidődben melyik áll hozzád legközelebb?',
    answers: [
      { id: 'A', text: 'Új appokat, AI toolokat, pluginokat tesztelek', scores: { kiserletezo: 2 } },
      { id: 'B', text: 'Reddit/TikTok/niche közösségekben böngészek, trendeket figyelek', scores: { kulturakutato: 2 } },
      { id: 'C', text: 'Saját projekteken dolgozom, ahol nincs korlát', scores: { vizionarius: 2 } },
      { id: 'D', text: 'Rendszerezek, rendet rakok, listákat készítek', scores: { rendszerepito: 2 } },
      { id: 'E', text: 'Tutorial videókat nézek, technikákat gyakorlok', scores: { kivitelezo: 2 } },
    ],
  },
  {
    id: 4,
    text: 'A kliens azt mondja: "Valahogy nem tetszik ez a szín." Mit csinálsz?',
    answers: [
      { id: 'A', text: 'Kérdezek: "Mi az érzés, amit szeretnél? Prémium? Játékos? Megbízható?"', scores: { hid: 2 } },
      { id: 'B', text: 'Megnézem, milyen színeket használnak a versenytársak és a célpiac', scores: { kulturakutato: 2, stratega: 1 } },
      { id: 'C', text: 'Gyorsan készítek 5-6 variációt, hadd válasszon', scores: { kivitelezo: 2, kameleon: 1 } },
      { id: 'D', text: 'Megkérdezem, hogy egyáltalán jó irányba megyünk-e a koncepcióval', scores: { vizionarius: 2 } },
      { id: 'E', text: 'Megnézem, hogyan illeszkedik a szín a teljes rendszerbe', scores: { rendszerepito: 2 } },
    ],
  },
  {
    id: 5,
    text: 'Ha választhatnál egy "szuperképességet", melyik lenne?',
    answers: [
      { id: 'A', text: 'Bármilyen stílusban tudok dolgozni, mintha mindig is az enyém lett volna', scores: { kameleon: 2 } },
      { id: 'B', text: 'Átlátom a nagy képet és a stratégiai összefüggéseket', scores: { stratega: 2 } },
      { id: 'C', text: 'Olyan ötleteim vannak, amiket még senki nem látott', scores: { vizionarius: 2 } },
      { id: 'D', text: 'Megértem, mit akar valójában mondani a kliens (még ha ő maga sem tudja)', scores: { hid: 2 } },
      { id: 'E', text: 'Bármilyen rendszert, bármilyen komplexitást át tudok látni', scores: { rendszerepito: 2 } },
    ],
  },
  {
    id: 6,
    text: 'A projekt melyik fázisát szereted a legjobban?',
    answers: [
      { id: 'A', text: 'Discovery, kutatás – amikor még mindent felfedezünk', scores: { kulturakutato: 2, vizionarius: 1 } },
      { id: 'B', text: 'Koncepció – amikor a nagy irányokat fektetjük le', scores: { stratega: 2, vizionarius: 1 } },
      { id: 'C', text: 'Design – amikor végre alkotok', scores: { kameleon: 2, kivitelezo: 1 } },
      { id: 'D', text: 'Kivitelezés – amikor pixel-pontosra csiszolom', scores: { kivitelezo: 2 } },
      { id: 'E', text: 'Rendszerezés – amikor mindent a helyére teszek', scores: { rendszerepito: 2 } },
    ],
  },
  {
    id: 7,
    text: 'Megjelenik egy új design tool. Mi a reakciód?',
    answers: [
      { id: 'A', text: 'Rögtön kipróbálom, még mielőtt bárki más a csapatban', scores: { kiserletezo: 2 } },
      { id: 'B', text: 'Megvárom, míg stabil lesz, aztán alaposan megtanulom', scores: { kivitelezo: 2 } },
      { id: 'C', text: 'Megnézem, hogy gyorsítja-e a workflow-t vagy jobb rendszereket építhetek vele', scores: { rendszerepito: 2, kiserletezo: 1 } },
      { id: 'D', text: 'Ha a végeredmény ugyanaz, nem fontos, milyen toollal csinálom', scores: { vizionarius: 1, stratega: 1, kameleon: 1 } },
      { id: 'E', text: 'Megnézem, hogy a kliensprezentáción mennyire lesz hasznos', scores: { hid: 2 } },
    ],
  },
  {
    id: 8,
    text: 'Ha nem designerként dolgoznál, mi lennél leginkább?',
    answers: [
      { id: 'A', text: 'Színész vagy előadóművész', scores: { kameleon: 2 } },
      { id: 'B', text: 'Mérnök vagy programozó', scores: { rendszerepito: 2, kivitelezo: 1 } },
      { id: 'C', text: 'Művész vagy filmrendező', scores: { vizionarius: 2 } },
      { id: 'D', text: 'Újságíró vagy antropológus', scores: { kulturakutato: 2 } },
      { id: 'E', text: 'Tanácsadó vagy coach', scores: { hid: 2, stratega: 1 } },
      { id: 'F', text: 'Feltaláló vagy startup alapító', scores: { kiserletezo: 2, stratega: 1 } },
    ],
  },
  {
    id: 9,
    text: 'Milyen az álomprojekted?',
    answers: [
      { id: 'A', text: 'Ahol teljesen szabad kezet kapok, és valami újat alkothatok', scores: { vizionarius: 2 } },
      { id: 'B', text: 'Ahol komplex rendszert kell felépítenem a nulláról', scores: { rendszerepito: 2 } },
      { id: 'C', text: 'Ahol mélyen bele kell ásnom magam egy szubkultúrába vagy piacba', scores: { kulturakutato: 2 } },
      { id: 'D', text: 'Ahol a legújabb technológiákat használhatom', scores: { kiserletezo: 2 } },
      { id: 'E', text: 'Ahol kristálytiszta a brief és a határidő', scores: { kivitelezo: 2 } },
      { id: 'F', text: 'Ahol összekapcsolhatom a kreatív csapatot az üzleti döntéshozókkal', scores: { hid: 2, stratega: 1 } },
    ],
  },
];

export const combinationTips: Record<string, string> = {
  'vizionarius_stratega': 'A Vízionárius + Stratéga páros ritka és értékes: nagy ötleteid vannak, de közben az üzleti logikát is látod. Ez azt jelenti, hogy nem csak álmodozol, hanem meg is tudod indokolni, miért érdemes egy irányba menni.',
  'stratega_vizionarius': 'A Stratéga + Vízionárius kombináció azt jelenti, hogy a nagy képet látod, és kreatívan is tudod megközelíteni. Nemcsak elemzel, hanem inspirálsz is.',
  'kameleon_kivitelezo': 'A Kaméleon + Kivitelező kombináció a stúdiók álma: bármilyen stílusban tudsz dolgozni, és még időben is kész vagy. A veszély? Túl sokat vállalsz, mert mindenre igent mondasz.',
  'kivitelezo_kameleon': 'A Kivitelező + Kaméleon kombináció azt jelenti, hogy nemcsak gyors vagy, de rugalmas is. Bármilyen projektet kapsz, megcsinálod – és jól.',
  'rendszerepito_stratega': 'A Rendszerépítő + Stratéga együtt a komplex projektek mestere. Te nemcsak megérted a nagy képet, de le is tudod bontani működő részekre.',
  'stratega_rendszerepito': 'A Stratéga + Rendszerépítő kombináció azt jelenti, hogy látod a célt és az odavezető utat is. Ritka képesség, amit a csapatok nagyra értékelnek.',
  'kulturakutato_vizionarius': 'A Kultúrakutató + Vízionárius kombináció a trendek pionírja. Nemcsak látod, mi jön, de új irányokba is tudod vinni.',
  'vizionarius_kulturakutato': 'A Vízionárius + Kultúrakutató kombináció azt jelenti, hogy a nagy ötleteid kulturálisan is relevánsak. Tudod, mit akar a közönség, még mielőtt ők tudnák.',
  'hid_stratega': 'A Híd + Stratéga kombináció a projektek titkos fegyvere. Nemcsak közvetítesz, hanem a stratégiai döntéseket is tudod kommunikálni.',
  'stratega_hid': 'A Stratéga + Híd kombináció azt jelenti, hogy látod a nagy képet és el is tudod magyarázni másoknak. Értékesíteni tudsz, nemcsak gondolkodni.',
  'kiserletezo_rendszerepito': 'A Kísérletező + Rendszerépítő kombináció azt jelenti, hogy az új toolokat nemcsak kipróbálod, hanem be is építed a workflow-ba. Innovátor és építő egyben.',
  'rendszerepito_kiserletezo': 'A Rendszerépítő + Kísérletező kombináció a hatékonyság bajnoka. A rendszereid mindig a legújabb lehetőségeket használják ki.',
  'default': 'Ez a kombináció egyedi erősségeket ad: ismerd meg mindkét típusod, és keresd azokat a projekteket, ahol mindkettőt használhatod!',
};
